summertodosite/config/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'))
]

summertodosite/user/urls.py
from django.shortcuts import redirect
from django.urls import include, path
from .views import GoalsDeleteView, MainRedirectView, MyGoalsView, GoalsFinishView

urlpatterns = [
    path('', MainRedirectView.as_view()),
    path('authentication/', include('allauth.urls')),
    path('my-goals/', MyGoalsView.as_view()),
    path('goal-delete/<int:pk>/', GoalsDeleteView.as_view(), name='goal-delete'),
    path('goal-finish/<int:pk>/', GoalsFinishView.as_view(), name='goal-finish'),

]

summertodosite/user/models.py
from django.db import models
from django.conf import settings



class goal(models.Model):
    sequence_choices = [
        ('Right now', 'Right now'),
        ('1', 'First'),
        ('2', 'Second'),
        ('3', 'Third'),
        ('4', 'Fourth'),
        ('5', 'Fifth'),
        ('6', 'Sixth'),
        ('7', 'Seventh'),
        ('8', 'Eighth'),
        ('9', 'Nineth'),
        ('10', 'Tenth'),
    ]

    executor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=60, blank=True, null=False, help_text="Text your goal here...")
    priority = models.CharField(choices=sequence_choices, default='Right now', max_length=10)
    status = models.CharField(default="In progress", blank=False, max_length=20)

    def get_absolute_url(self):
        return '/my-goals/'

summertodosite/user/forms.py
import email
from django import forms
from django.forms import ModelForm, CharField
from .models import goal
from allauth.account.forms import SignupForm, LoginForm

class CreateGoalForm(ModelForm):
    class Meta:
        model = goal
        fields = ['title', 'priority', ]


class SignUpForm(SignupForm):

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for fieldname, field in self.fields.items():
            field.widget.attrs.update({
                'class':'form-control'
            })

    def save(self, request):
        user = super(SignUpForm, self).save(request)
        return user

class MyLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(MyLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget.attrs.update({
            'class':'form-control' })
        self.fields['password'].widget.attrs.update({
        'class':'form-control' })
            

                

summertodosite/user/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import FormView, DeleteView, View
from .forms import CreateGoalForm
from django.core.paginator import Paginator
from .models import goal
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


class MainRedirectView(View):

    def get(self, *args, **kwargs):
        return redirect('/my-goals/')


class MyGoalsView(LoginRequiredMixin, FormView):
    model = goal
    template_name = "interface/my_goals.html"
    context_object_name = 'user'
    form_class = CreateGoalForm
    success_url = '/my-goals/'
    login_url = '/authentication/login/'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        goals = goal.objects.filter(
            executor=self.request.user.id).order_by('-status')
        paginator = Paginator(goals, 5)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        page_list = []
        for i in range(page_obj.paginator.num_pages):
            i += 1
            page_list.append(i)

        context['user_goals'] = goals
        context['page_obj'] = page_obj
        context['page_list'] = page_list
        return context

    def form_valid(self, form):
        form = form.save(commit=False)
        form.executor = self.request.user
        form.save()
        return super(MyGoalsView, self).form_valid(form)


class GoalsDeleteView(PermissionRequiredMixin, DeleteView):
    model = goal
    template_name = "interface/goal_delete.html"
    context_object_name = 'goal'
    success_url = "/"
    permission_required = 'user.delete_goal'

    def has_permission(self):
        has_perms = super().has_permission()
        pk = self.kwargs['pk']
        post = get_object_or_404(goal, pk=pk)
        self.object = self.get_object()
        user_is_executor = self.object.executor == self.request.user
        return user_is_executor


class GoalsFinishView(View):
    model = goal
    template_name = "interface/goal_finish.html"
    context_object_name = 'goal'
    success_url = '/'

    def get(self, *args, **kwargs):
        pk = self.kwargs['pk']
        post = get_object_or_404(goal, pk=pk)

        if self.request.user == post.executor:
            post.status = 'Finished'
            post.save()
            return redirect("/my-goals/")
        else:
            return redirect('/my-goals/')

summertodosite/user/templates/interface/goal_delete.html
{% load static %}
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <title>Goal Delete Page</title>
</head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-7 col-xl-9">
          <div class="card rounded-3">
            <div class="card-body p-4">
  
              <h4 class="text-center my-3 pb-3">Summer To Do App</h4>
  
              <form action="" method="POST" class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
                <div class="col-12">
                <div class="form-outline">
                  {% csrf_token %}
                    <p style="margin-left: 210px;">Are you sure you want to delete "{{ goal.title }}"?</p>
                    {{ form }}
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary" style="font-family: 'Noto Sans', sans-serif;">Confirm</button>
                    </div>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

summertodosite/user/templates/interface/goal_finish.html
{% load static %}
<head>
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <title>Goal Finish Page</title>
</head>

summertodosite/user/templates/interface/my_goals.html
{% load static %}

<head>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300&display=swap" rel="stylesheet">
  <title>My goals</title>
</head>

<style>
  @media screen and (min-width: 1080px) and (max-width: 2440px) {

    .pagination_rounded,
    .pagination_square {
      display: inline-block;
      margin-left: 320px;
      margin-top: 25px;
    }

    .pagination_rounded ul li {
      float: left;
      margin-left: 20px;
    }

    .pagination_rounded .prev {
      margin-left: 0px;
      border-radius: 35px;
      width: 90px;
      height: 34px;
      line-height: 34px;
    }

    .pagination_rounded ul li a {
      float: left;
      color: #4285f4;
      border-radius: 50%;
      line-height: 30px;
      height: 30px;
      width: 30px;
      text-align: center;
      margin-bottom: 40px;
      border: 1px solid #e0e0e0;
    }

    .pagination_rounded .prev i {
      -right: 10px;
    }

    .pagination_rounded .next {
      border-radius: 35px;
      width: 90px;
      height: 34px;
      line-height: 34px;
    }


  }

  @media screen and (min-width: 992px) and (max-width: 1079px) {

    .pagination_rounded,
    .pagination_square {
      display: inline-block;
      margin-left: 320px;
      margin-top: 25px;
    }

    .pagination_rounded ul li {
      float: left;
      margin-left: 20px;
    }

    .pagination_rounded .prev {
      margin-left: 0px;
      border-radius: 35px;
      width: 90px;
      height: 34px;
      line-height: 34px;
    }

    .pagination_rounded ul li a {
      float: left;
      color: #4285f4;
      border-radius: 50%;
      line-height: 30px;
      height: 30px;
      width: 30px;
      text-align: center;
      margin-bottom: 40px;
      border: 1px solid #e0e0e0;
    }

    .pagination_rounded .prev i {
      -right: 10px;
    }

    .pagination_rounded .next {
      border-radius: 35px;
      width: 90px;
      height: 34px;
      line-height: 34px;
    }

  }

  .pagination_rounded ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  .pagination_rounded li:first-child {
    margin-left: 0px;
  }


  .pagination_rounded ul li a:hover {
    background: #4285f4;
    color: #fff;
    border: 1px solid #4285f4;
  }

  a:link {
    text-decoration: none;
  }

  .visible-xs {
    display: none !important;
  }
</style>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<section class="vh-100" style="background-color: #eee;">

  <div id="cont" class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-7 col-xl-9">
        <div class="card rounded-3">
          <div class="card-body p-4">
            <h4 class="text-center my-3 pb-3">Summer To Do App</h4>

            <form action="" method="POST"
              class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
              <div class="col-12">
                <div class="form-outline">
                  {% csrf_token %}

                  <p> <input type="text" name="title" maxlength="60" id="id_title" placeholder="Text your goal here..."
                      class="form-control"></p>
                  <select name="priority" id="id_priority" style="margin-top:10px; margin-bottom:15px;"
                    class="form-control">
                    <option value="Right now" selected="">Right now</option>

                    <option value="1">First</option>

                    <option value="2">Second</option>

                    <option value="3">Third</option>

                    <option value="4">Fourth</option>

                    <option value="5">Fifth</option>

                    <option value="6">Sixth</option>

                    <option value="7">Seventh</option>

                    <option value="8">Eighth</option>

                    <option value="9">Nineth</option>

                    <option value="10">Tenth</option>

                  </select>

                </div>
              </div>

              <div class="col-12">
                <button type="submit" class="btn btn-primary"
                  style="font-family: 'Noto Sans', sans-serif;">Save</button>
              </div>

            </form>

            <table class="table mb-4">
              <thead>
                <tr>
                  <th scope="col">Sq.</th>
                  <th scope="col">Todo item</th>
                  <th scope="col">Status</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for i in page_obj %}
                <tr>
                  <th scope="row">{{ i.priority }}</th>
                  <td>{{ i.title }}</td>
                  <td>{{ i.status }}</td>
                  <td>
                    <a href="{% url 'goal-delete' pk=i.pk %}"><button type="submit" class="btn btn-danger" name="delete"
                        value="">Delete</button></a>
                    <a href="{% url 'goal-finish' pk=i.pk %}"><button type="submit" class="btn btn-success ms-1"
                        name="done">Finished</button></a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <div class="pagination_rounded">
              <ul>
                {% for i in page_list %}
                <li>
                  <a href="?page={{i}}">{{ i }}</a>
                </li>
                {% endfor %}
              </ul>
            </div>
            <p><a class="text-center my-3 pb-3" href="https://www.flaticon.com/free-icons/list" title="list icons">List
                icons created by Freepik - Flaticon</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
</section>